type LegacyProject = {
  id: string;
  title: string;
  category: string;
  year: string;
  imageUrl: string;
  coverImageUrl?: string;
  description: string;
  tags: string[];
  galleryImages?: string[];
  x: number;
  y: number;
  width: number;
  height: number;
};

// Temporary gallery placeholders so the project-detail interactions can be
// exercised against both single-image and multi-image cases.
const placeholderDetailGalleries = {
  lumina: [
    "https://images.unsplash.com/photo-1720962158883-b0f2021fb51e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmdXR1cmlzdGljJTIwdGVjaG5vbG9neSUyMGludGVyZmFjZXxlbnwxfHx8fDE3NzA0NjQwNTR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1575388902449-6bca946ad549?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWJzaXRlJTIwZGFzaGJvYXJkJTIwaW50ZXJmYWNlJTIwZGVzaWdufGVufDF8fHx8MTc3MDU0MjE1OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1741466071751-c62474d2d3ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b3Jrc3BhY2UlMjBkZXNrJTIwc2V0dXAlMjBjcmVhdGl2ZXxlbnwxfHx8fDE3NzA1NDIxNzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
  ],
  apex: [
    "https://images.unsplash.com/photo-1596742578443-7682ef5251cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBhcHAlMjBVSSUyMGRlc2lnbiUyMGRhcmt8ZW58MXx8fHwxNzcwNTM2MDQwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1720962158883-b0f2021fb51e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmdXR1cmlzdGljJTIwdGVjaG5vbG9neSUyMGludGVyZmFjZXxlbnwxfHx8fDE3NzA0NjQwNTR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1598296087805-0eedb25ce2d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZXJpYWwlMjBjaXR5JTIwcGhvdG9ncmFwaHklMjBuaWdodHxlbnwxfHx8fDE3NzA1NDIxNzN8MA&ixlib=rb-4.1.0&q=80&w=1080",
  ],
  maison: [
    "https://images.unsplash.com/photo-1558707538-c56435bdcdf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsJTIwcG9zdGVyJTIwdHlwb2dyYXBoeSUyMGRlc2lnbnxlbnwxfHx8fDE3NzA1NDIxNjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1560087459-7665dcbd23c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVhdGl2ZSUyMGRpcmVjdGlvbiUyMGVkaXRvcmlhbCUyMGxheW91dHxlbnwxfHx8fDE3NzA1NDIxNjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1629380321696-99d97eaa492a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwcG90dGVyeSUyMGhhbmRtYWRlJTIwY3JhZnR8ZW58MXx8fHwxNzcwNTQyMTc0fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ],
  studioSetup: [
    "https://images.unsplash.com/photo-1575388902449-6bca946ad549?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWJzaXRlJTIwZGFzaGJvYXJkJTIwaW50ZXJmYWNlJTIwZGVzaWdufGVufDF8fHx8MTc3MDU0MjE1OXww&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1705321963943-de94bb3f0dd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwbGl2aW5nJTIwcm9vbSUyMGludGVyaW9yJTIwZGVzaWdufGVufDF8fHx8MTc3MDU0MTY2MXww&ixlib=rb-4.1.0&q=80&w=1080",
    "https://images.unsplash.com/photo-1722977735215-d28f2ac6efba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib29rc3RvcmUlMjBsaWJyYXJ5JTIwc2hlbHZlcyUyMHdhcm18ZW58MXx8fHwxNzcwNTQyMTc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ],
} as const;

export const projects: LegacyProject[] = [
  {
    id: "1",
    title: "Lumina App",
    category: "Mobile Design",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1596742578443-7682ef5251cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBhcHAlMjBVSSUyMGRlc2lnbiUyMGRhcmt8ZW58MXx8fHwxNzcwNTM2MDQwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "A mindfulness and wellness app designed with dark mode aesthetics. The interface focuses on calm interactions, smooth transitions, and an intuitive journaling experience that helps users track their mental health journey.",
    tags: ["UI/UX", "Mobile", "Wellness"],
    galleryImages: placeholderDetailGalleries.lumina,
    x: 80, y: 60, width: 320, height: 240,
  },
  {
    id: "2",
    title: "Apex Dashboard",
    category: "Web Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1575388902449-6bca946ad549?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWJzaXRlJTIwZGFzaGJvYXJkJTIwaW50ZXJmYWNlJTIwZGVzaWdufGVufDF8fHx8MTc3MDU0MjE1OXww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "An analytics dashboard for a SaaS fintech platform. Designed to present complex financial data through clear visualizations, real-time metrics, and customizable widget layouts.",
    tags: ["Dashboard", "SaaS", "Data Viz"],
    galleryImages: placeholderDetailGalleries.apex,
    x: 480, y: 30, width: 360, height: 260,
  },
  {
    id: "3",
    title: "Maison Brand",
    category: "Brand Identity",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1616205255812-c07c8102cc02?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicmFuZCUyMGlkZW50aXR5JTIwZGVzaWduJTIwbW9ja3VwfGVufDF8fHx8MTc3MDUyODU3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Complete brand identity system for a luxury home furnishing company. Includes logo suite, color system, typography guidelines, packaging design, and digital asset templates.",
    tags: ["Branding", "Identity", "Luxury"],
    galleryImages: placeholderDetailGalleries.maison,
    x: 930, y: 80, width: 280, height: 350,
  },
  {
    id: "4",
    title: "Ethereal",
    category: "3D & Motion",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1634618948828-aa7b3d0724fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMDNEJTIwcmVuZGVyJTIwY29sb3JmdWx8ZW58MXx8fHwxNzcwNTQyMTYwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Experimental 3D renders exploring organic forms and iridescent materials. Created for a digital art exhibition showcasing the intersection of technology and natural beauty.",
    tags: ["3D", "Art Direction", "Experimental"],
    x: 1320, y: 40, width: 300, height: 220,
  },
  {
    id: "5",
    title: "Typo Festival",
    category: "Print Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1558707538-c56435bdcdf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsJTIwcG9zdGVyJTIwdHlwb2dyYXBoeSUyMGRlc2lnbnxlbnwxfHx8fDE3NzA1NDIxNjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Poster series for an international typography festival. Each poster experiments with letterform as visual element, blurring the line between type and image through scale and abstraction.",
    tags: ["Typography", "Print", "Poster"],
    x: 1720, y: 90, width: 260, height: 340,
  },
  {
    id: "6",
    title: "Bloom Packaging",
    category: "Packaging",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1655568560328-17285eff8d7e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9kdWN0JTIwcGFja2FnaW5nJTIwZGVzaWduJTIwbW9kZXJufGVufDF8fHx8MTc3MDU0MjE2MXww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Sustainable packaging design for an organic tea brand. Focused on tactile materials, earthy color palette, and illustrations that celebrate the origin story of each blend.",
    tags: ["Packaging", "Sustainability", "Illustration"],
    x: 2070, y: 50, width: 320, height: 240,
  },
  {
    id: "7",
    title: "Prism",
    category: "Visual Identity",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1766431546350-686a34c5b979?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnZW9tZXRyaWMlMjBhYnN0cmFjdCUyMGdyYWRpZW50JTIwYXJ0fGVufDF8fHx8MTc3MDU0MjE2MXww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "A generative visual identity system for a creative technology conference. The identity evolves through algorithmic patterns, with each application being unique yet cohesive.",
    tags: ["Generative", "Identity", "Tech"],
    x: 2490, y: 70, width: 280, height: 210,
  },
  {
    id: "8",
    title: "Casa Interior",
    category: "Spatial Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1765207296039-7ffc2c4b0716?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcmNoaXRlY3R1cmUlMjBpbnRlcmlvciUyMG1vZGVybiUyMHNwYWNlfGVufDF8fHx8MTc3MDU0MjE2Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Interior visualization for a boutique hotel in Lisbon. Blending Portuguese craftsmanship with contemporary design, each room tells a story through materiality and light.",
    tags: ["Interior", "Architecture", "Hospitality"],
    x: 2860, y: 30, width: 340, height: 260,
  },
  {
    id: "9",
    title: "Atelier Editorial",
    category: "Editorial",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1560087459-7665dcbd23c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVhdGl2ZSUyMGRpcmVjdGlvbiUyMGVkaXRvcmlhbCUyMGxheW91dHxlbnwxfHx8fDE3NzA1NDIxNjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Art direction for a biannual design magazine. Developed the editorial system including grid structures, typographic hierarchy, and photographic direction across 120 pages.",
    tags: ["Editorial", "Art Direction", "Print"],
    x: 70, y: 380, width: 340, height: 250,
  },
  {
    id: "10",
    title: "Neon Nights",
    category: "Photography",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1769940887654-e3b9a5e06ae5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZW9uJTIwbGlnaHRzJTIwdmlicmFudCUyMHB1cnBsZXxlbnwxfHx8fDE3NzA1NDIxNjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "A photographic series exploring urban nightlife through neon-lit environments. Shot across Tokyo, Seoul, and Hong Kong, capturing the electric atmosphere of cities that never sleep.",
    tags: ["Photography", "Urban", "Light"],
    x: 520, y: 370, width: 280, height: 360,
  },
  {
    id: "11",
    title: "Silhouette",
    category: "Fashion",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1668952135116-2bcd8a9a2f8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwcGhvdG9ncmFwaHklMjBlZGl0b3JpYWwlMjBzdHVkaW98ZW58MXx8fHwxNzcwNTQyMTY2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Campaign art direction for a sustainable fashion label. Minimal studio shots emphasizing form and texture, celebrating slow fashion and thoughtful consumption.",
    tags: ["Fashion", "Campaign", "Sustainability"],
    x: 920, y: 510, width: 300, height: 230,
  },
  {
    id: "12",
    title: "Chromatic",
    category: "Art Direction",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1636220409261-794e0464ca2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMHBhaW50JTIwdGV4dHVyZSUyMGNvbG9yZnVsfGVufDF8fHx8MTc3MDU0MjE2Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Abstract paintings commissioned for a corporate lobby. Large-scale works exploring color field theory and emotional response, translating the company's values into pure visual language.",
    tags: ["Fine Art", "Commission", "Abstract"],
    x: 1310, y: 340, width: 320, height: 240,
  },
  {
    id: "13",
    title: "Nexus Interface",
    category: "UI Design",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1720962158883-b0f2021fb51e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmdXR1cmlzdGljJTIwdGVjaG5vbG9neSUyMGludGVyZmFjZXxlbnwxfHx8fDE3NzA0NjQwNTR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Futuristic control interface for an autonomous vehicle concept. Designed for heads-up display with gesture-based interactions, prioritizing safety and minimal cognitive load.",
    tags: ["Automotive", "HUD", "Futuristic"],
    x: 1700, y: 510, width: 300, height: 220,
  },
  {
    id: "14",
    title: "Chronos",
    category: "Product Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1670177257750-9b47927f68eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjB3YXRjaCUyMHByb2R1Y3QlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NzA1MzQ3MzR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Product photography and visual language for a luxury watch brand relaunch. Shot with dramatic lighting to emphasize craftsmanship, with a design system spanning digital and print.",
    tags: ["Luxury", "Product", "Photography"],
    x: 2085, y: 370, width: 290, height: 370,
  },
  {
    id: "15",
    title: "Zen Garden",
    category: "Environmental",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1762932922297-767ca87bfe3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxKYXBhbmVzZSUyMHplbiUyMGdhcmRlbiUyMG1pbmltYWx8ZW58MXx8fHwxNzcwNTQyMTY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Landscape design documentation for a meditation retreat in Kyoto. Capturing the interplay of stone, water, and light that defines Japanese zen aesthetics.",
    tags: ["Landscape", "Japanese", "Minimal"],
    x: 2480, y: 360, width: 300, height: 230,
  },
  {
    id: "16",
    title: "Roast & Co",
    category: "Brand Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1758709859167-c5b61778b714?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2ZmZWUlMjBzaG9wJTIwYnJhbmRpbmclMjBhZXN0aGV0aWN8ZW58MXx8fHwxNzcwNTQyMTY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Full brand identity for a specialty coffee roastery. From logo and packaging to interior signage and digital presence, creating a warm and inviting brand world.",
    tags: ["F&B", "Branding", "Packaging"],
    x: 2860, y: 370, width: 340, height: 250,
  },
  {
    id: "17",
    title: "Golden Hour",
    category: "Photography",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1543550311-4aefe188a95b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdW5zZXQlMjBvY2VhbiUyMGxhbmRzY2FwZSUyMGdvbGRlbnxlbnwxfHx8fDE3NzA1NDIxNzF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "A landscape photography series capturing the fleeting moments of sunset across coastal locations. Each image explores how light transforms familiar landscapes into otherworldly scenes.",
    tags: ["Landscape", "Photography", "Nature"],
    x: 60, y: 710, width: 360, height: 260,
  },
  {
    id: "18",
    title: "Stride",
    category: "Product Launch",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1768647417374-5a31c61dc5d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbmVha2VyJTIwcHJvZHVjdCUyMGRlc2lnbiUyMGNsb3NlfGVufDF8fHx8MTc3MDU0MjE3Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Visual campaign for a sneaker launch blending athletic performance with streetwear culture. Created the campaign identity, social assets, and retail experience design.",
    tags: ["Sneakers", "Campaign", "Retail"],
    x: 520, y: 810, width: 280, height: 210,
  },
  {
    id: "19",
    title: "White Space",
    category: "Exhibition",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1549272427-4fd45418a8c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNldW0lMjBnYWxsZXJ5JTIwd2hpdGUlMjBzcGFjZXxlbnwxfHx8fDE3NzA1NDIxNzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Exhibition design for a contemporary art gallery. Curated the spatial flow, lighting design, and visitor experience to create contemplative moments between artworks.",
    tags: ["Exhibition", "Curation", "Spatial"],
    x: 915, y: 820, width: 310, height: 240,
  },
  {
    id: "20",
    title: "Verdant",
    category: "Visual Design",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1622003874000-c9541292651c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0cm9waWNhbCUyMHBsYW50cyUyMGdyZWVuJTIwbGVhdmVzfGVufDF8fHx8MTc3MDU0MjE3M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Visual identity for a botanical garden rebrand. Lush photography paired with elegant typography creates a system that celebrates biodiversity and environmental stewardship.",
    tags: ["Botanical", "Identity", "Green"],
    x: 1325, y: 660, width: 290, height: 370,
  },
  {
    id: "21",
    title: "Glow Skincare",
    category: "Product Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1505830623932-d9d4d8089283?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3NtZXRpY3MlMjBiZWF1dHklMjBwcm9kdWN0JTIwbWluaW1hbHxlbnwxfHx8fDE3NzA1MDE2MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Packaging and digital design for a clean beauty brand. Minimal aesthetic with a focus on ingredient transparency and sustainable materials.",
    tags: ["Beauty", "Packaging", "Minimal"],
    x: 1700, y: 810, width: 300, height: 230,
  },
  {
    id: "22",
    title: "Metropolis",
    category: "Photography",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1598296087805-0eedb25ce2d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZXJpYWwlMjBjaXR5JTIwcGhvdG9ncmFwaHklMjBuaWdodHxlbnwxfHx8fDE3NzA1NDIxNzN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Aerial photography series of major cities at night. Shot from helicopters and rooftops, these images reveal the hidden geometry and energy patterns of urban landscapes.",
    tags: ["Aerial", "Urban", "Night"],
    x: 2060, y: 820, width: 340, height: 250,
  },
  {
    id: "23",
    title: "Analog",
    category: "Music & Culture",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1594328082907-cd93c1c518d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aW55bCUyMHJlY29yZCUyMG11c2ljJTIwcmV0cm98ZW58MXx8fHwxNzcwNTQyMTc0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Album artwork series for an indie record label. Each cover is a handcrafted collage combining analog photography with digital textures, reflecting the label's ethos.",
    tags: ["Music", "Album Art", "Collage"],
    x: 2490, y: 670, width: 280, height: 350,
  },
  {
    id: "24",
    title: "Terra Ceramics",
    category: "Product",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1629380321696-99d97eaa492a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwcG90dGVyeSUyMGhhbmRtYWRlJTIwY3JhZnR8ZW58MXx8fHwxNzcwNTQyMTc0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Brand photography and e-commerce design for a ceramics studio. Warm, tactile imagery paired with a clean digital storefront that honors the handmade process.",
    tags: ["Craft", "E-commerce", "Photography"],
    x: 2870, y: 700, width: 320, height: 240,
  },
  {
    id: "25",
    title: "Studio Setup",
    category: "Workspace",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1741466071751-c62474d2d3ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b3Jrc3BhY2UlMjBkZXNrJTIwc2V0dXAlMjBjcmVhdGl2ZXxlbnwxfHx8fDE3NzA1NDIxNzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Documentation of creative workspaces around the world. A photographic essay exploring how environment shapes creativity, from minimalist studios to chaotic workshops.",
    tags: ["Documentary", "Workspace", "Creative"],
    galleryImages: placeholderDetailGalleries.studioSetup,
    x: 90, y: 1050, width: 300, height: 230,
  },
  {
    id: "26",
    title: "Summit",
    category: "Photography",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1701483807362-ea0136c7526c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3VudGFpbiUyMGxhbmRzY2FwZSUyMGRyYW1hdGljJTIwZm9nfGVufDF8fHx8MTc3MDU0MjE3OHww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Mountain landscape series shot during expeditions in Patagonia and the Dolomites. Dramatic compositions that capture the raw power and solitude of high-altitude environments.",
    tags: ["Landscape", "Mountains", "Adventure"],
    x: 485, y: 1100, width: 350, height: 260,
  },
  {
    id: "27",
    title: "Cuvee",
    category: "Label Design",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1700893417257-c87e3d2857a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aW5lJTIwYm90dGxlJTIwbGFiZWwlMjBkZXNpZ258ZW58MXx8fHwxNzcwNTQyMTc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Wine label collection for a family-owned vineyard in Tuscany. Each vintage has a unique illustrated label inspired by the terroir and seasonal character of the harvest.",
    tags: ["Wine", "Label", "Illustration"],
    x: 930, y: 1140, width: 280, height: 350,
  },
  {
    id: "28",
    title: "Velocity",
    category: "Automotive",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1759377104288-d23cba3e51b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhdXRvbW90aXZlJTIwY2FyJTIwc3R1ZGlvJTIwc2hvdHxlbnwxfHx8fDE3NzA1NDIxNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Visual campaign for an electric vehicle launch. Studio photography with dynamic lighting that highlights the vehicle's sculptural form and innovation in sustainable mobility.",
    tags: ["Automotive", "Campaign", "EV"],
    x: 1300, y: 1110, width: 340, height: 250,
  },
  {
    id: "29",
    title: "Woven",
    category: "Textile Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1655149238677-9b5cb1a0afc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZXh0aWxlJTIwcGF0dGVybiUyMGZhYnJpYyUyMGNsb3NldXB8ZW58MXx8fHwxNzcwNTQyMTc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Textile pattern collection for an interiors brand. Inspired by Japanese sashiko stitching and Scandinavian weaving traditions, creating a bridge between craft cultures.",
    tags: ["Textile", "Pattern", "Interiors"],
    x: 1705, y: 1120, width: 290, height: 220,
  },
  {
    id: "30",
    title: "Chapter & Verse",
    category: "Retail Design",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1722977735215-d28f2ac6efba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib29rc3RvcmUlMjBsaWJyYXJ5JTIwc2hlbHZlcyUyMHdhcm18ZW58MXx8fHwxNzcwNTQyMTc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Interior and brand design for an independent bookstore. Created a warm, inviting space that encourages exploration, with custom shelving, wayfinding, and a cafe concept.",
    tags: ["Retail", "Interior", "Bookstore"],
    x: 2070, y: 1150, width: 320, height: 240,
  },
  {
    id: "31",
    title: "Street Culture",
    category: "Photography",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1616778504552-194fe8daad79?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXR3ZWFyJTIwdXJiYW4lMjBzdHlsZSUyMHBob3RvZ3JhcGh5fGVufDF8fHx8MTc3MDU0MjE4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Documentary photography series on global street culture and fashion. Shot in London, Lagos, and Los Angeles, exploring how personal style reflects cultural identity.",
    tags: ["Street", "Fashion", "Documentary"],
    x: 2480, y: 1100, width: 300, height: 360,
  },
  {
    id: "32",
    title: "Omakase",
    category: "Hospitality",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1669131196140-49591336b13e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjByZXN0YXVyYW50JTIwaW50ZXJpb3IlMjBkZXNpZ258ZW58MXx8fHwxNzcwNDYyMDUzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Complete brand and interior design for a modern Japanese restaurant. From the menu system to the materiality of the space, every detail reflects the precision of omakase dining.",
    tags: ["Restaurant", "Japanese", "Interior"],
    x: 2875, y: 1020, width: 310, height: 240,
  },
  {
    id: "33",
    title: "Refract",
    category: "Architecture",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1714601344981-75e003bc5d18?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnbGFzcyUyMGFyY2hpdGVjdHVyZSUyMHJlZmxlY3Rpb258ZW58MXx8fHwxNzcwNTQyMTgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Architectural photography series focusing on glass facades and their reflections. Exploring how modern buildings create abstract compositions through transparency and light.",
    tags: ["Architecture", "Glass", "Abstract"],
    x: 85, y: 1360, width: 310, height: 240,
  },
  {
    id: "34",
    title: "Pure",
    category: "Product Design",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1665763630810-e6251bdd392d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxza2luY2FyZSUyMGJvdHRsZSUyMHdoaXRlJTIwYmFja2dyb3VuZHxlbnwxfHx8fDE3NzA1NDIxODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Minimalist product photography for a skincare line. Clean white backgrounds with precise lighting to hero the bottle forms and brand's commitment to simplicity.",
    tags: ["Skincare", "Minimal", "Product"],
    x: 520, y: 1440, width: 280, height: 350,
  },
  {
    id: "35",
    title: "Spectrum",
    category: "Mural Art",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1769613758100-a5d12762b1ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmZ1bCUyMG11cmFsJTIwc3RyZWV0JTIwYXJ0JTIwd2FsbHxlbnwxfHx8fDE3NzA1NDIxODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Large-scale mural installations for public spaces. Vibrant, community-engaged art that transforms blank walls into landmarks, bringing color and conversation to neighborhoods.",
    tags: ["Mural", "Public Art", "Community"],
    x: 900, y: 1570, width: 340, height: 250,
  },
  {
    id: "36",
    title: "Sahara",
    category: "Photography",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1669024513552-56127b2d0d85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNlcnQlMjBzYW5kJTIwZHVuZXMlMjBsYW5kc2NhcGV8ZW58MXx8fHwxNzcwNDk2NTY3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Desert landscape photography exploring the sculptural beauty of sand dunes. The play of light and shadow creates ever-changing compositions in the world's most minimal landscape.",
    tags: ["Desert", "Landscape", "Minimal"],
    x: 1310, y: 1440, width: 320, height: 240,
  },
  {
    id: "37",
    title: "Verso Magazine",
    category: "Editorial",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1766239303199-b45e6bcdc901?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWdhemluZSUyMGVkaXRvcmlhbCUyMHNwcmVhZCUyMGxheW91dHxlbnwxfHx8fDE3NzA1NDIxODV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Design direction for Verso, an independent culture magazine. Bold layouts with experimental typography that push the boundaries of traditional editorial design.",
    tags: ["Magazine", "Editorial", "Typography"],
    x: 1705, y: 1420, width: 290, height: 370,
  },
  {
    id: "38",
    title: "Resonance",
    category: "Product Design",
    year: "2026",
    imageUrl: "https://images.unsplash.com/photo-1761005654142-819960af0658?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFkcGhvbmVzJTIwYXVkaW8lMjBwcm9kdWN0JTIwZGFya3xlbnwxfHx8fDE3NzA1NDIxODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Product design and campaign for premium wireless headphones. Dark, moody photography that communicates sound quality through visual atmosphere and precise detail shots.",
    tags: ["Audio", "Product", "Campaign"],
    x: 2075, y: 1470, width: 310, height: 230,
  },
  {
    id: "39",
    title: "Living Room",
    category: "Interior Design",
    year: "2025",
    imageUrl: "https://images.unsplash.com/photo-1705321963943-de94bb3f0dd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwbGl2aW5nJTIwcm9vbSUyMGludGVyaW9yJTIwZGVzaWdufGVufDF8fHx8MTc3MDU0MTY2MXww&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Residential interior design for a penthouse apartment. Neutral palette with statement furniture pieces, emphasizing natural light and spatial flow throughout open-plan living areas.",
    tags: ["Residential", "Interior", "Luxury"],
    x: 2460, y: 1540, width: 340, height: 250,
  },
  {
    id: "40",
    title: "Dried Botanicals",
    category: "Still Life",
    year: "2024",
    imageUrl: "https://images.unsplash.com/photo-1753583572865-7f75623c3114?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmllZCUyMGZsb3dlcnMlMjBtaW5pbWFsJTIwYXJyYW5nZW1lbnR8ZW58MXx8fHwxNzcwNTQxNjY0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    description: "Still life photography series celebrating the beauty of dried botanicals. Shot with natural light on neutral backgrounds, exploring texture, form, and the elegance of impermanence.",
    tags: ["Still Life", "Botanical", "Photography"],
    x: 2890, y: 1340, width: 280, height: 360,
  },
];
