import type { Project } from "./types";

// Generated by `npm run sync:dribbble:local`. This keeps the public
// portfolio fully local-first for static hosting while the admin panel code
// remains in the repo for future use.
export const localPortfolioProjects: Omit<Project, "x" | "y" | "width" | "height">[] = [
  {
    "id": "dribbble-shot-24567439",
    "title": "Car HMI - Digital Instrument Cluster",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/24567439/00-card-car-hmi-digital-instrument-cluster.webp",
    "coverImageUrl": "/portfolio/dribbble/24567439/01-car-hmi-digital-instrument-cluster.png",
    "description": "Hey Dribbble! Created a Car HMI - Instrument Cluster\n\nThis was my first time recreating and learning the process of making a HMI Digital Cluster. Inspired and recreated the work of Daniil Bondarenko.\n\nLink to his work HMI Digital Cluster.\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/24567439/02-car-hmi-digital-instrument-cluster.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-24567439",
        "content": "<h2>Overview</h2><p>Hey Dribbble! Created a Car HMI - Instrument Cluster</p><p>This was my first time recreating and learning the process of making a HMI Digital Cluster. Inspired and recreated the work of Daniil Bondarenko.</p><p>Link to his work HMI Digital Cluster.</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-23934044",
    "title": "Camera App Interface",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/23934044/00-card-camera-app-interface.webp",
    "coverImageUrl": "/portfolio/dribbble/23934044/01-camera-app-interface.png",
    "description": "Tried to recreate a DSLR interface for the Camera App\n\nMade on Figma\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/23934044/02-camera-app-interface.png",
      "/portfolio/dribbble/23934044/03-camera-app-interface.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-23934044",
        "content": "<h2>Overview</h2><p>Tried to recreate a DSLR interface for the Camera App</p><p>Made on Figma</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-23668419",
    "title": "Pricing Plan Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/23668419/00-card-pricing-plan-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/23668419/01-pricing-plan-concept.png",
    "description": "Hey Dribbble! Created a simple pricing plan for a website\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/23668419/02-pricing-plan-concept.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-23668419",
        "content": "<h2>Overview</h2><p>Hey Dribbble! Created a simple pricing plan for a website</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-23655497",
    "title": "Teenage Engineering Style Calculator",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/23655497/00-card-teenage-engineering-style-calculator.webp",
    "coverImageUrl": "/portfolio/dribbble/23655497/01-teenage-engineering-style-calculator.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/23655497/02-teenage-engineering-style-calculator.png",
      "/portfolio/dribbble/23655497/03-teenage-engineering-style-calculator.png",
      "/portfolio/dribbble/23655497/04-teenage-engineering-style-calculator.png",
      "/portfolio/dribbble/23655497/05-teenage-engineering-style-calculator.png",
      "/portfolio/dribbble/23655497/06-teenage-engineering-style-calculator.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-23654092",
    "title": "Kickflips Website",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/23654092/00-card-kickflips-website.webp",
    "coverImageUrl": "/portfolio/dribbble/23654092/01-kickflips-website.png",
    "description": "Hey Dribbble! Created a shoe selling website\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/23654092/02-kickflips-website.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-23654092",
        "content": "<h2>Overview</h2><p>Hey Dribbble! Created a shoe selling website</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-23437307",
    "title": "Shipper Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/23437307/00-card-shipper-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/23437307/01-shipper-dashboard.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/23437307/02-shipper-dashboard.png",
      "/portfolio/dribbble/23437307/03-shipper-dashboard.png",
      "/portfolio/dribbble/23437307/04-shipper-dashboard.png",
      "/portfolio/dribbble/23437307/05-shipper-dashboard.png",
      "/portfolio/dribbble/23437307/06-shipper-dashboard.png",
      "/portfolio/dribbble/23437307/07-shipper-dashboard.png",
      "/portfolio/dribbble/23437307/08-shipper-dashboard.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-23168492",
    "title": "Bento Features Grid",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/23168492/00-card-bento-features-grid.webp",
    "coverImageUrl": "/portfolio/dribbble/23168492/01-bento-features-grid.png",
    "description": "Hey Dribbble! Recently created a features grid AI based writing website. Made using elements from Align UI.\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/23168492/02-bento-features-grid.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-23168492",
        "content": "<h2>Overview</h2><p>Hey Dribbble! Recently created a features grid AI based writing website. Made using elements from Align UI.</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22957848",
    "title": "Design System - Features Grid",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22957848/00-card-design-system-features-grid.webp",
    "coverImageUrl": "/portfolio/dribbble/22957848/01-design-system-features-grid.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22957848/02-design-system-features-grid.png",
      "/portfolio/dribbble/22957848/03-design-system-features-grid.png",
      "/portfolio/dribbble/22957848/04-design-system-features-grid.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22938084",
    "title": "Features Grid - Light Mode",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22938084/00-card-features-grid-light-mode.webp",
    "coverImageUrl": "/portfolio/dribbble/22938084/01-features-grid-light-mode.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22938084/02-features-grid-light-mode.png",
      "/portfolio/dribbble/22938084/03-features-grid-light-mode.png",
      "/portfolio/dribbble/22938084/04-features-grid-light-mode.png",
      "/portfolio/dribbble/22938084/05-features-grid-light-mode.png",
      "/portfolio/dribbble/22938084/06-features-grid-light-mode.png",
      "/portfolio/dribbble/22938084/07-features-grid-light-mode.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22758523",
    "title": "Food Recipe Mobile App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22758523/00-card-food-recipe-mobile-app.webp",
    "coverImageUrl": "/portfolio/dribbble/22758523/01-food-recipe-mobile-app.png",
    "description": "Hi everybody\n\nThis is my exploration of Food Recipe App",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22758523/02-food-recipe-mobile-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22758523",
        "content": "<h2>Overview</h2><p>Hi everybody</p><p>This is my exploration of Food Recipe App</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22757609",
    "title": "Serenity Studio Website",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22757609/00-card-serenity-studio-website.webp",
    "coverImageUrl": "/portfolio/dribbble/22757609/01-serenity-studio-website.png",
    "description": "Serenity Studio is your sanctuary for mindful movement and holistic well-being, offering diverse classes, experienced instructors, and a welcoming community to elevate your yoga journey.\n\nThis is my exploration for its website.\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22757609/02-serenity-studio-website.png",
      "/portfolio/dribbble/22757609/03-serenity-studio-website.png",
      "/portfolio/dribbble/22757609/04-serenity-studio-website.png",
      "/portfolio/dribbble/22757609/05-serenity-studio-website.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22757609",
        "content": "<h2>Overview</h2><p>Serenity Studio is your sanctuary for mindful movement and holistic well-being, offering diverse classes, experienced instructors, and a welcoming community to elevate your yoga journey.</p><p>This is my exploration for its website.</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22678544",
    "title": "Mailbox - Email Client Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22678544/00-card-mailbox-email-client-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/22678544/01-mailbox-email-client-concept.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22678544/02-mailbox-email-client-concept.png",
      "/portfolio/dribbble/22678544/03-mailbox-email-client-concept.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22656144",
    "title": "Très Chic | Fashion App Ver 2",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22656144/00-card-tres-chic-fashion-app-ver-2.webp",
    "coverImageUrl": "/portfolio/dribbble/22656144/01-tres-chic-fashion-app-ver-2.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22656144/02-tres-chic-fashion-app-ver-2.png",
      "/portfolio/dribbble/22656144/03-tres-chic-fashion-app-ver-2.png",
      "/portfolio/dribbble/22656144/04-tres-chic-fashion-app-ver-2.png",
      "/portfolio/dribbble/22656144/05-tres-chic-fashion-app-ver-2.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22639417",
    "title": "Oculus - Card Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22639417/00-card-oculus-card-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/22639417/01-oculus-card-dashboard.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22639417/02-oculus-card-dashboard.png",
      "/portfolio/dribbble/22639417/03-oculus-card-dashboard.png",
      "/portfolio/dribbble/22639417/04-oculus-card-dashboard.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22555280",
    "title": "Features Grid",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22555280/00-card-features-grid.webp",
    "coverImageUrl": "/portfolio/dribbble/22555280/01-features-grid.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22555280/02-features-grid.png",
      "/portfolio/dribbble/22555280/03-features-grid.png",
      "/portfolio/dribbble/22555280/04-features-grid.png",
      "/portfolio/dribbble/22555280/05-features-grid.png",
      "/portfolio/dribbble/22555280/06-features-grid.png",
      "/portfolio/dribbble/22555280/07-features-grid.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22508441",
    "title": "Volvo Car App - Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22508441/00-card-volvo-car-app-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/22508441/01-volvo-car-app-concept.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22508441/02-volvo-car-app-concept.png",
      "/portfolio/dribbble/22508441/03-volvo-car-app-concept.png",
      "/portfolio/dribbble/22508441/04-volvo-car-app-concept.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22468642",
    "title": "Dyson Link App - Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22468642/00-card-dyson-link-app-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/22468642/01-dyson-link-app-concept.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22468642/02-dyson-link-app-concept.png",
      "/portfolio/dribbble/22468642/03-dyson-link-app-concept.png",
      "/portfolio/dribbble/22468642/04-dyson-link-app-concept.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22455857",
    "title": "Online Code Compiler - Features Bento Grid",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22455857/00-card-online-code-compiler-features-bento-grid.webp",
    "coverImageUrl": "/portfolio/dribbble/22455857/01-online-code-compiler-features-bento-grid.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22455857/02-online-code-compiler-features-bento-grid.png",
      "/portfolio/dribbble/22455857/03-online-code-compiler-features-bento-grid.png",
      "/portfolio/dribbble/22455857/04-online-code-compiler-features-bento-grid.png",
      "/portfolio/dribbble/22455857/05-online-code-compiler-features-bento-grid.png",
      "/portfolio/dribbble/22455857/06-online-code-compiler-features-bento-grid.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22521040",
    "title": "Arch. Website V2",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22521040/00-card-arch-website-v2.webp",
    "coverImageUrl": "/portfolio/dribbble/22521040/01-arch-website-v2.png",
    "description": "Hi everybody\n\nThis is my exploration of an interior firm website\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22521040/01-arch-website-v2-motion.gif",
      "/portfolio/dribbble/22521040/02-arch-website-v2.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22521040",
        "content": "<h2>Overview</h2><p>Hi everybody</p><p>This is my exploration of an interior firm website</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22499065",
    "title": "Crypto Platform - Concept App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22499065/00-card-crypto-platform-concept-app.webp",
    "coverImageUrl": "/portfolio/dribbble/22499065/01-crypto-platform-concept-app.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22499065/02-crypto-platform-concept-app.png",
      "/portfolio/dribbble/22499065/03-crypto-platform-concept-app.png",
      "/portfolio/dribbble/22499065/04-crypto-platform-concept-app.png",
      "/portfolio/dribbble/22499065/05-crypto-platform-concept-app.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22420180",
    "title": "VisionBlend - AI 3D Tool ✏️",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22420180/00-card-visionblend-ai-3d-tool.webp",
    "coverImageUrl": "/portfolio/dribbble/22420180/01-visionblend-ai-3d-tool.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22420180/01-visionblend-ai-3d-tool-motion.gif",
      "/portfolio/dribbble/22420180/02-visionblend-ai-3d-tool-motion.gif",
      "/portfolio/dribbble/22420180/03-visionblend-ai-3d-tool-motion.gif",
      "/portfolio/dribbble/22420180/04-visionblend-ai-3d-tool-motion.gif",
      "/portfolio/dribbble/22420180/02-visionblend-ai-3d-tool.png",
      "/portfolio/dribbble/22420180/03-visionblend-ai-3d-tool.png",
      "/portfolio/dribbble/22420180/04-visionblend-ai-3d-tool.png",
      "/portfolio/dribbble/22420180/05-visionblend-ai-3d-tool.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22342452",
    "title": "Card Payments App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22342452/00-card-card-payments-app.webp",
    "coverImageUrl": "/portfolio/dribbble/22342452/01-card-payments-app.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22342452/02-card-payments-app.png",
      "/portfolio/dribbble/22342452/03-card-payments-app.png",
      "/portfolio/dribbble/22342452/04-card-payments-app.png",
      "/portfolio/dribbble/22342452/05-card-payments-app.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22345228",
    "title": "Dyson Link - Dynamic Island Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22345228/00-card-dyson-link-dynamic-island-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/22345228/01-dyson-link-dynamic-island-concept.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22345228/01-dyson-link-dynamic-island-concept-motion.gif",
      "/portfolio/dribbble/22345228/02-dyson-link-dynamic-island-concept.png",
      "/portfolio/dribbble/22345228/03-dyson-link-dynamic-island-concept.png",
      "/portfolio/dribbble/22345228/04-dyson-link-dynamic-island-concept.png",
      "/portfolio/dribbble/22345228/05-dyson-link-dynamic-island-concept.png",
      "/portfolio/dribbble/22345228/06-dyson-link-dynamic-island-concept.png",
      "/portfolio/dribbble/22345228/07-dyson-link-dynamic-island-concept.png",
      "/portfolio/dribbble/22345228/08-dyson-link-dynamic-island-concept.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22284584",
    "title": "Arch. Website",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22284584/00-card-arch-website.webp",
    "coverImageUrl": "/portfolio/dribbble/22284584/01-arch-website.png",
    "description": "Hi everybody\n\nThis is my exploration of an interior firm website\n\nDo let me know 💬 what you think !\n\nPress\"L\" to Like ❤️ the Post.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22284584/01-arch-website-motion.gif",
      "/portfolio/dribbble/22284584/02-arch-website.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22284584",
        "content": "<h2>Overview</h2><p>Hi everybody</p><p>This is my exploration of an interior firm website</p><p>Do let me know 💬 what you think !</p><p>Press&quot;L&quot; to Like ❤️ the Post.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22278980",
    "title": "Stock Investment App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22278980/00-card-stock-investment-app.webp",
    "coverImageUrl": "/portfolio/dribbble/22278980/01-stock-investment-app.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22278980/02-stock-investment-app.png",
      "/portfolio/dribbble/22278980/03-stock-investment-app.png",
      "/portfolio/dribbble/22278980/04-stock-investment-app.png",
      "/portfolio/dribbble/22278980/05-stock-investment-app.png",
      "/portfolio/dribbble/22278980/06-stock-investment-app.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22238556",
    "title": "Casio Twin Graph",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22238556/00-card-casio-twin-graph.webp",
    "coverImageUrl": "/portfolio/dribbble/22238556/01-casio-twin-graph.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22238556/02-casio-twin-graph.png",
      "/portfolio/dribbble/22238556/03-casio-twin-graph.png",
      "/portfolio/dribbble/22238556/04-casio-twin-graph.png",
      "/portfolio/dribbble/22238556/05-casio-twin-graph.png",
      "/portfolio/dribbble/22238556/06-casio-twin-graph.png",
      "/portfolio/dribbble/22238556/07-casio-twin-graph.png",
      "/portfolio/dribbble/22238556/08-casio-twin-graph.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22233960",
    "title": "Vision Arc Studio FOLIO",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22233960/00-card-vision-arc-studio-folio.webp",
    "coverImageUrl": "/portfolio/dribbble/22233960/01-vision-arc-studio-folio.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22233960/01-vision-arc-studio-folio-motion.gif",
      "/portfolio/dribbble/22233960/02-vision-arc-studio-folio.png",
      "/portfolio/dribbble/22233960/03-vision-arc-studio-folio.png",
      "/portfolio/dribbble/22233960/04-vision-arc-studio-folio.png",
      "/portfolio/dribbble/22233960/05-vision-arc-studio-folio.png",
      "/portfolio/dribbble/22233960/06-vision-arc-studio-folio.png",
      "/portfolio/dribbble/22233960/07-vision-arc-studio-folio.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22212066",
    "title": "Onboarding screens - Illustrations",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22212066/00-card-onboarding-screens-illustrations.webp",
    "coverImageUrl": "/portfolio/dribbble/22212066/01-onboarding-screens-illustrations.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22212066/01-onboarding-screens-illustrations-motion.gif",
      "/portfolio/dribbble/22212066/02-onboarding-screens-illustrations.png",
      "/portfolio/dribbble/22212066/03-onboarding-screens-illustrations.png",
      "/portfolio/dribbble/22212066/04-onboarding-screens-illustrations.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22196841",
    "title": "Lourve Museum Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22196841/00-card-lourve-museum-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/22196841/01-lourve-museum-concept.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22196841/02-lourve-museum-concept.png",
      "/portfolio/dribbble/22196841/03-lourve-museum-concept.png",
      "/portfolio/dribbble/22196841/04-lourve-museum-concept.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22157142",
    "title": "Lourve Museum Concept",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22157142/00-card-lourve-museum-concept.webp",
    "coverImageUrl": "/portfolio/dribbble/22157142/01-lourve-museum-concept.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22157142/01-lourve-museum-concept-motion.gif",
      "/portfolio/dribbble/22157142/02-lourve-museum-concept.png",
      "/portfolio/dribbble/22157142/03-lourve-museum-concept.png",
      "/portfolio/dribbble/22157142/04-lourve-museum-concept.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22150430",
    "title": "Weather App V.2",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22150430/00-card-weather-app-v2.webp",
    "coverImageUrl": "/portfolio/dribbble/22150430/01-weather-app-v2.png",
    "description": "Recently i created a weather app with dark mode background. Today i recreated it with a light mode background. This app is created to check the forecast for your current location or search for a specific city. View hourly and weekly predictions, including temperature, precipitation, and more. Stay ahead of the weather and plan your day with confidence with our easy-to-use app.\n\nDo let me know what you think !",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22150430/02-weather-app-v2.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22150430",
        "content": "<h2>Overview</h2><p>Recently i created a weather app with dark mode background. Today i recreated it with a light mode background. This app is created to check the forecast for your current location or search for a specific city. View hourly and weekly predictions, including temperature, precipitation, and more. Stay ahead of the weather and plan your day with confidence with our easy-to-use app.</p><p>Do let me know what you think !</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22096634",
    "title": "Travel Landing Page",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22096634/00-card-travel-landing-page.webp",
    "coverImageUrl": "/portfolio/dribbble/22096634/01-travel-landing-page.png",
    "description": "Introducing Tripp. our new Travel Booking Destination\n\nDo let me know what you think ! Press \" L\" to Like",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22096634/01-travel-landing-page-motion.gif",
      "/portfolio/dribbble/22096634/02-travel-landing-page.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22096634",
        "content": "<h2>Overview</h2><p>Introducing Tripp. our new Travel Booking Destination</p><p>Do let me know what you think ! Press &quot; L&quot; to Like</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22080366",
    "title": "Boosted Boards - Ecommerce App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22080366/00-card-boosted-boards-ecommerce-app.webp",
    "coverImageUrl": "/portfolio/dribbble/22080366/01-boosted-boards-ecommerce-app.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22080366/02-boosted-boards-ecommerce-app.png",
      "/portfolio/dribbble/22080366/03-boosted-boards-ecommerce-app.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22071620",
    "title": "Fitness & Health Tracker",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22071620/00-card-fitness-health-tracker.webp",
    "coverImageUrl": "/portfolio/dribbble/22071620/01-fitness-health-tracker.png",
    "description": "I recently made an app to track fitness and health.\n\nTried to give it a dark feel.\n\nPlease let me know what you think.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22071620/02-fitness-health-tracker.png",
      "/portfolio/dribbble/22071620/03-fitness-health-tracker.png",
      "/portfolio/dribbble/22071620/04-fitness-health-tracker.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-22071620",
        "content": "<h2>Overview</h2><p>I recently made an app to track fitness and health.</p><p>Tried to give it a dark feel.</p><p>Please let me know what you think.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-22063458",
    "title": "Zenflow - HR Management Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22063458/00-card-zenflow-hr-management-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/22063458/01-zenflow-hr-management-dashboard.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22063458/02-zenflow-hr-management-dashboard.png",
      "/portfolio/dribbble/22063458/03-zenflow-hr-management-dashboard.png",
      "/portfolio/dribbble/22063458/04-zenflow-hr-management-dashboard.png",
      "/portfolio/dribbble/22063458/05-zenflow-hr-management-dashboard.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22022498",
    "title": "Podcast : Apple Vision Os",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22022498/00-card-podcast-apple-vision-os.webp",
    "coverImageUrl": "/portfolio/dribbble/22022498/01-podcast-apple-vision-os.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22022498/02-podcast-apple-vision-os.png",
      "/portfolio/dribbble/22022498/03-podcast-apple-vision-os.png",
      "/portfolio/dribbble/22022498/04-podcast-apple-vision-os.png",
      "/portfolio/dribbble/22022498/05-podcast-apple-vision-os.png",
      "/portfolio/dribbble/22022498/06-podcast-apple-vision-os.png",
      "/portfolio/dribbble/22022498/07-podcast-apple-vision-os.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-22016014",
    "title": "HMI Car Dashboard - Hyundai Ioniq 5",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/22016014/00-card-hmi-car-dashboard-hyundai-ioniq-5.webp",
    "coverImageUrl": "/portfolio/dribbble/22016014/01-hmi-car-dashboard-hyundai-ioniq-5.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/22016014/02-hmi-car-dashboard-hyundai-ioniq-5.png",
      "/portfolio/dribbble/22016014/03-hmi-car-dashboard-hyundai-ioniq-5.png",
      "/portfolio/dribbble/22016014/04-hmi-car-dashboard-hyundai-ioniq-5.png",
      "/portfolio/dribbble/22016014/05-hmi-car-dashboard-hyundai-ioniq-5.png",
      "/portfolio/dribbble/22016014/06-hmi-car-dashboard-hyundai-ioniq-5.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-21991116",
    "title": "Galaxy Watch | Analog Watch Face",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/21991116/00-card-galaxy-watch-analog-watch-face.webp",
    "coverImageUrl": "/portfolio/dribbble/21991116/01-galaxy-watch-analog-watch-face.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/21991116/02-galaxy-watch-analog-watch-face.png",
      "/portfolio/dribbble/21991116/03-galaxy-watch-analog-watch-face.png",
      "/portfolio/dribbble/21991116/04-galaxy-watch-analog-watch-face.png",
      "/portfolio/dribbble/21991116/05-galaxy-watch-analog-watch-face.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-21793905",
    "title": "Vital - Fitness & Health Tracker",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/21793905/00-card-vital-fitness-health-tracker.webp",
    "coverImageUrl": "/portfolio/dribbble/21793905/01-vital-fitness-health-tracker.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/21793905/02-vital-fitness-health-tracker.png",
      "/portfolio/dribbble/21793905/03-vital-fitness-health-tracker.png",
      "/portfolio/dribbble/21793905/04-vital-fitness-health-tracker.png",
      "/portfolio/dribbble/21793905/05-vital-fitness-health-tracker.png",
      "/portfolio/dribbble/21793905/06-vital-fitness-health-tracker.png",
      "/portfolio/dribbble/21793905/07-vital-fitness-health-tracker.png",
      "/portfolio/dribbble/21793905/08-vital-fitness-health-tracker.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-21556503",
    "title": "NOMOS Glashütte Watch Face",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/21556503/00-card-nomos-glashutte-watch-face.webp",
    "coverImageUrl": "/portfolio/dribbble/21556503/01-nomos-glashutte-watch-face.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/21556503/02-nomos-glashutte-watch-face.png",
      "/portfolio/dribbble/21556503/03-nomos-glashutte-watch-face.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-21172537",
    "title": "Interior AI Landing Page",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/21172537/00-card-interior-ai-landing-page.webp",
    "coverImageUrl": "/portfolio/dribbble/21172537/01-interior-ai-landing-page.png",
    "description": "Introducing Interior AI, the ultimate AI-powered platform for interior design. With Interior AI, users can create custom interior designs using advanced AI algorithms that analyze their unique preferences and style.\n\nOur platform offers features such as 3D visualization, personalized design suggestions, and a vast library of design products to choose from. Join Interior AI today and revolutionize the way you design your dream interior.\n\nLet me know what you think !!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/21172537/02-interior-ai-landing-page.png",
      "/portfolio/dribbble/21172537/03-interior-ai-landing-page.png",
      "/portfolio/dribbble/21172537/04-interior-ai-landing-page.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-21172537",
        "content": "<h2>Overview</h2><p>Introducing Interior AI, the ultimate AI-powered platform for interior design. With Interior AI, users can create custom interior designs using advanced AI algorithms that analyze their unique preferences and style.</p><p>Our platform offers features such as 3D visualization, personalized design suggestions, and a vast library of design products to choose from. Join Interior AI today and revolutionize the way you design your dream interior.</p><p>Let me know what you think !!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20987786",
    "title": "Odyssey - SaaS Landing Page",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20987786/00-card-odyssey-saas-landing-page.webp",
    "coverImageUrl": "/portfolio/dribbble/20987786/01-odyssey-saas-landing-page.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20987786/02-odyssey-saas-landing-page.png",
      "/portfolio/dribbble/20987786/03-odyssey-saas-landing-page.png",
      "/portfolio/dribbble/20987786/04-odyssey-saas-landing-page.png",
      "/portfolio/dribbble/20987786/05-odyssey-saas-landing-page.png",
      "/portfolio/dribbble/20987786/06-odyssey-saas-landing-page.png",
      "/portfolio/dribbble/20987786/07-odyssey-saas-landing-page.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-20984790",
    "title": "Odyssey - Finance Dashboard  💳",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20984790/00-card-odyssey-finance-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/20984790/01-odyssey-finance-dashboard.png",
    "description": "Odyssey is a new fintech dashboard with its user-friendly interface. Users can easily navigate through their spending and transactions data from multiple websites, gaining valuable insights into their financial habits. The dashboard provides clear and concise visualizations of data, making it easy to identify trends and patterns in spending behavior. Odyssey offers a seamless and intuitive experience for users looking to manage their finances in one centralized location.\n\nLet me know what you think about it !!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20984790/02-odyssey-finance-dashboard.png",
      "/portfolio/dribbble/20984790/03-odyssey-finance-dashboard.png",
      "/portfolio/dribbble/20984790/04-odyssey-finance-dashboard.png",
      "/portfolio/dribbble/20984790/05-odyssey-finance-dashboard.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20984790",
        "content": "<h2>Overview</h2><p>Odyssey is a new fintech dashboard with its user-friendly interface. Users can easily navigate through their spending and transactions data from multiple websites, gaining valuable insights into their financial habits. The dashboard provides clear and concise visualizations of data, making it easy to identify trends and patterns in spending behavior. Odyssey offers a seamless and intuitive experience for users looking to manage their finances in one centralized location.</p><p>Let me know what you think about it !!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20967323",
    "title": "Neptune - Credit Card Website",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20967323/00-card-neptune-credit-card-website.webp",
    "coverImageUrl": "/portfolio/dribbble/20967323/01-neptune-credit-card-website.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20967323/02-neptune-credit-card-website.png",
      "/portfolio/dribbble/20967323/03-neptune-credit-card-website.png",
      "/portfolio/dribbble/20967323/04-neptune-credit-card-website.png",
      "/portfolio/dribbble/20967323/05-neptune-credit-card-website.png",
      "/portfolio/dribbble/20967323/06-neptune-credit-card-website.png",
      "/portfolio/dribbble/20967323/07-neptune-credit-card-website.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-20954511",
    "title": "Mobile App - Furniture Ecommerce",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20954511/00-card-mobile-app-furniture-ecommerce.webp",
    "coverImageUrl": "/portfolio/dribbble/20954511/01-mobile-app-furniture-ecommerce.png",
    "description": "Introducing our brand new Furniture E-Commerce Mobile App - the one-stop destination for all your furniture needs!\n\nWith our app, you can easily browse through a vast collection of high-quality furniture products, ranging from contemporary to traditional designs, and everything in between.\n\nOur app is designed to provide a seamless and hassle-free shopping experience, with easy navigation and intuitive user interface.\n\nLet me know what you think about it!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20954511/02-mobile-app-furniture-ecommerce.png",
      "/portfolio/dribbble/20954511/03-mobile-app-furniture-ecommerce.png",
      "/portfolio/dribbble/20954511/04-mobile-app-furniture-ecommerce.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20954511",
        "content": "<h2>Overview</h2><p>Introducing our brand new Furniture E-Commerce Mobile App - the one-stop destination for all your furniture needs!</p><p>With our app, you can easily browse through a vast collection of high-quality furniture products, ranging from contemporary to traditional designs, and everything in between.</p><p>Our app is designed to provide a seamless and hassle-free shopping experience, with easy navigation and intuitive user interface.</p><p>Let me know what you think about it!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20479794",
    "title": "Très Chic | Fashion E-commerce App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20479794/00-card-tres-chic-fashion-e-commerce-app.webp",
    "coverImageUrl": "/portfolio/dribbble/20479794/01-tres-chic-fashion-e-commerce-app.png",
    "description": "Introducing Très Chic, the ultimate fashion app for the stylish and trend-savvy. Discover the latest fashion trends, shop your favorite brands, and curate your own wardrobe with ease. With Très Chic, you'll always stay on top of the latest fashion and never miss a beat.\n\nDo let me know what you think about it !",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20479794/02-tres-chic-fashion-e-commerce-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20479794",
        "content": "<h2>Overview</h2><p>Introducing Très Chic, the ultimate fashion app for the stylish and trend-savvy. Discover the latest fashion trends, shop your favorite brands, and curate your own wardrobe with ease. With Très Chic, you&#39;ll always stay on top of the latest fashion and never miss a beat.</p><p>Do let me know what you think about it !</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20407925",
    "title": "Stark | Mobile Finance App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20407925/00-card-stark-mobile-finance-app.webp",
    "coverImageUrl": "/portfolio/dribbble/20407925/01-stark-mobile-finance-app.png",
    "description": "Introducing our sleek and user-friendly finance app!\n\nEasily check your card balance, send money to friends and family, and stay on top of your spending with detailed transaction statistics. Keep your finances organized and in check with Stark\n\nDo let me know what you think about this !!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20407925/02-stark-mobile-finance-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20407925",
        "content": "<h2>Overview</h2><p>Introducing our sleek and user-friendly finance app!</p><p>Easily check your card balance, send money to friends and family, and stay on top of your spending with detailed transaction statistics. Keep your finances organized and in check with Stark</p><p>Do let me know what you think about this !!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20402794",
    "title": "Weather App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20402794/00-card-weather-app.webp",
    "coverImageUrl": "/portfolio/dribbble/20402794/01-weather-app.png",
    "description": "Get ready for your day with our accurate and reliable weather app. Check the forecast for your current location or search for a specific city. View hourly and weekly predictions, including temperature, precipitation, and more. Stay ahead of the weather and plan your day with confidence with our easy-to-use app.\n\nDo let me know what you think !",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20402794/02-weather-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20402794",
        "content": "<h2>Overview</h2><p>Get ready for your day with our accurate and reliable weather app. Check the forecast for your current location or search for a specific city. View hourly and weekly predictions, including temperature, precipitation, and more. Stay ahead of the weather and plan your day with confidence with our easy-to-use app.</p><p>Do let me know what you think !</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20282039",
    "title": "Quest - Smart Home Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20282039/00-card-quest-smart-home-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/20282039/01-quest-smart-home-dashboard.png",
    "description": "Hello everyone!\n\nQuest is a smart home app that allows users to manage all of their smart home devices from a single app.\n\nUsers may take control of all of their devices and manage them conveniently.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20282039/02-quest-smart-home-dashboard.png",
      "/portfolio/dribbble/20282039/03-quest-smart-home-dashboard.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20282039",
        "content": "<h2>Overview</h2><p>Hello everyone!</p><p>Quest is a smart home app that allows users to manage all of their smart home devices from a single app.</p><p>Users may take control of all of their devices and manage them conveniently.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20254719",
    "title": "Bill Split App | Finance Manager",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20254719/00-card-bill-split-app-finance-manager.webp",
    "coverImageUrl": "/portfolio/dribbble/20254719/01-bill-split-app-finance-manager.png",
    "description": "Bill Split App Design! Hope you guys like it\n\nDo let me know what you think about it !",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20254719/02-bill-split-app-finance-manager.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20254719",
        "content": "<h2>Overview</h2><p>Bill Split App Design! Hope you guys like it</p><p>Do let me know what you think about it !</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20236777",
    "title": "Travel App Design 🛫",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20236777/00-card-travel-app-design.webp",
    "coverImageUrl": "/portfolio/dribbble/20236777/01-travel-app-design.png",
    "description": "Made a quick design for a travel app. Users are given the ability to book tickets and explore various travel destinations for them.\n\nLet me know what you think about this !",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20236777/02-travel-app-design.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20236777",
        "content": "<h2>Overview</h2><p>Made a quick design for a travel app. Users are given the ability to book tickets and explore various travel destinations for them.</p><p>Let me know what you think about this !</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20224517",
    "title": "Landing Page | Origin Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20224517/00-card-landing-page-origin-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/20224517/01-landing-page-origin-dashboard.png",
    "description": "Landing page for Origin Website. Origin is a convenient tool for users to keep track of their multiple cards and manage their spending.\n\nDo let me know what your think !",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20224517/02-landing-page-origin-dashboard.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20224517",
        "content": "<h2>Overview</h2><p>Landing page for Origin Website. Origin is a convenient tool for users to keep track of their multiple cards and manage their spending.</p><p>Do let me know what your think !</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20214262",
    "title": "Card Management Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20214262/00-card-card-management-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/20214262/01-card-management-dashboard.png",
    "description": "Card Management Dashboard is a powerful tool that allows you to add, manage, and track your cards. The intuitive interface and user-friendly design give you complete control over your cards and finances. Whether you're managing a single card or a whole portfolio, our dashboard has you covered.\n\nDo let me know what you think of this !!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20214262/02-card-management-dashboard.png",
      "/portfolio/dribbble/20214262/03-card-management-dashboard.png",
      "/portfolio/dribbble/20214262/04-card-management-dashboard.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20214262",
        "content": "<h2>Overview</h2><p>Card Management Dashboard is a powerful tool that allows you to add, manage, and track your cards. The intuitive interface and user-friendly design give you complete control over your cards and finances. Whether you&#39;re managing a single card or a whole portfolio, our dashboard has you covered.</p><p>Do let me know what you think of this !!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20198366",
    "title": "Formula 1 App - Dynamic Standing",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20198366/00-card-formula-1-app-dynamic-standing.webp",
    "coverImageUrl": "/portfolio/dribbble/20198366/01-formula-1-app-dynamic-standing.png",
    "description": "Introducing the new F1 App feature for iPhone 14 pro series users: the Dynamic Island Standings View! With this innovative feature, you can quickly and easily check on the current driver standings with just a few taps. Simply force touch on the dynamic island to expand the view and see the live standings in greater detail.\n\nLet me know what you think of this concept.",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20198366/01-formula-1-app-dynamic-standing-motion.gif",
      "/portfolio/dribbble/20198366/02-formula-1-app-dynamic-standing.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20198366",
        "content": "<h2>Overview</h2><p>Introducing the new F1 App feature for iPhone 14 pro series users: the Dynamic Island Standings View! With this innovative feature, you can quickly and easily check on the current driver standings with just a few taps. Simply force touch on the dynamic island to expand the view and see the live standings in greater detail.</p><p>Let me know what you think of this concept.</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20193058",
    "title": "Origin - Card Management Dashboard",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20193058/00-card-origin-card-management-dashboard.webp",
    "coverImageUrl": "/portfolio/dribbble/20193058/01-origin-card-management-dashboard.png",
    "description": "Origin is a convenient tool for users to keep track of their multiple cards and manage their spending. With this app, users can store all of their cards in one place and set limits for each individual card.\n\nThe dashboard also displays a record of all transactions made with the cards, making it easy for users to stay on top of their spending.\n\nWhether you have one card or multiple cards, the card management dashboard gives you the control you need to manage your finances effectively.\n\nI can't wait to hear your thoughts on the design!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20193058/02-origin-card-management-dashboard.png",
      "/portfolio/dribbble/20193058/03-origin-card-management-dashboard.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20193058",
        "content": "<h2>Overview</h2><p>Origin is a convenient tool for users to keep track of their multiple cards and manage their spending. With this app, users can store all of their cards in one place and set limits for each individual card.</p><p>The dashboard also displays a record of all transactions made with the cards, making it easy for users to stay on top of their spending.</p><p>Whether you have one card or multiple cards, the card management dashboard gives you the control you need to manage your finances effectively.</p><p>I can&#39;t wait to hear your thoughts on the design!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20162707",
    "title": "Crypto wallet - Mobile app",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20162707/00-card-crypto-wallet-mobile-app.webp",
    "coverImageUrl": "/portfolio/dribbble/20162707/01-crypto-wallet-mobile-app.png",
    "description": "Hey,\n\nAre you looking for some fresh perspective on your crypto wallet app's design? I'd love to hear your thoughts and offer my own insights!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20162707/02-crypto-wallet-mobile-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20162707",
        "content": "<h2>Overview</h2><p>Hey,</p><p>Are you looking for some fresh perspective on your crypto wallet app&#39;s design? I&#39;d love to hear your thoughts and offer my own insights!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20153260",
    "title": "Daily UI Design Challenge | Dropdown | Day 27",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20153260/00-card-daily-ui-design-challenge-dropdown-day-27.webp",
    "coverImageUrl": "/portfolio/dribbble/20153260/01-daily-ui-design-challenge-dropdown-day-27.png",
    "description": "Hey, This is my take on Daily UI challenge #025\n\nDropdown\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20153260/02-daily-ui-design-challenge-dropdown-day-27.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20153260",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #025</p><p>Dropdown</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20153236",
    "title": "Daily UI Design Challenge | Subscribe | Day 26",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20153236/00-card-daily-ui-design-challenge-subscribe-day-26.webp",
    "coverImageUrl": "/portfolio/dribbble/20153236/01-daily-ui-design-challenge-subscribe-day-26.png",
    "description": "Hey, This is my take on Daily UI challenge #026\n\nSubscribe\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20153236/02-daily-ui-design-challenge-subscribe-day-26.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20153236",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #026</p><p>Subscribe</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-20139517",
    "title": "Daily UI Design Challenge | TV App | Day 25",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/20139517/00-card-daily-ui-design-challenge-tv-app-day-25.webp",
    "coverImageUrl": "/portfolio/dribbble/20139517/01-daily-ui-design-challenge-tv-app-day-25.png",
    "description": "Hey, This is my take on Daily UI challenge #025\n\nTv App\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/20139517/02-daily-ui-design-challenge-tv-app-day-25.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-20139517",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #025</p><p>Tv App</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19831881",
    "title": "Daily UI Design Challenge |Boarding Pass | Day 24",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19831881/00-card-daily-ui-design-challenge-boarding-pass-day-24.webp",
    "coverImageUrl": "/portfolio/dribbble/19831881/01-daily-ui-design-challenge-boarding-pass-day-24.png",
    "description": "",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19831881/02-daily-ui-design-challenge-boarding-pass-day-24.png",
      "/portfolio/dribbble/19831881/03-daily-ui-design-challenge-boarding-pass-day-24.png",
      "/portfolio/dribbble/19831881/04-daily-ui-design-challenge-boarding-pass-day-24.png",
      "/portfolio/dribbble/19831881/05-daily-ui-design-challenge-boarding-pass-day-24.png"
    ],
    "contentBlocks": []
  },
  {
    "id": "dribbble-shot-19819504",
    "title": "Daily UI Design Challenge | Onboarding | Day 23",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19819504/00-card-daily-ui-design-challenge-onboarding-day-23.webp",
    "coverImageUrl": "/portfolio/dribbble/19819504/01-daily-ui-design-challenge-onboarding-day-23.png",
    "description": "Hey, This is my take on Daily UI challenge #023\n\nOnboarding\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19819504/02-daily-ui-design-challenge-onboarding-day-23.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19819504",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #023</p><p>Onboarding</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19819443",
    "title": "Daily UI Design Challenge | Search | Day 22",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19819443/00-card-daily-ui-design-challenge-search-day-22.webp",
    "coverImageUrl": "/portfolio/dribbble/19819443/01-daily-ui-design-challenge-search-day-22.png",
    "description": "Hey, This is my take on Daily UI challenge #022\n\nSearch Command\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19819443/02-daily-ui-design-challenge-search-day-22.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19819443",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #022</p><p>Search Command</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19729554",
    "title": "Daily UI Design Challenge | Home Monitoring Dashboard | Day 21",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19729554/00-card-daily-ui-design-challenge-home-monitoring-dashboard-day-21.webp",
    "coverImageUrl": "/portfolio/dribbble/19729554/01-daily-ui-design-challenge-home-monitoring-dashboard-day-21.png",
    "description": "Hey, This is my take on Daily UI challenge #021\n\nHome Monitoring Dashboard\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19729554/02-daily-ui-design-challenge-home-monitoring-dashboard-day-21.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19729554",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #021</p><p>Home Monitoring Dashboard</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19656054",
    "title": "Daily UI Design Challenge | Location Tracker | Day 020",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19656054/00-card-daily-ui-design-challenge-location-tracker-day-020.webp",
    "coverImageUrl": "/portfolio/dribbble/19656054/01-daily-ui-design-challenge-location-tracker-day-020.png",
    "description": "Hey, This is my take on Daily UI challenge #020\n\nLocation Tracker\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19656054/02-daily-ui-design-challenge-location-tracker-day-020.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19656054",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #020</p><p>Location Tracker</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19656041",
    "title": "Daily UI Design Challenge | Leaderboard | Day 019",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19656041/00-card-daily-ui-design-challenge-leaderboard-day-019.webp",
    "coverImageUrl": "/portfolio/dribbble/19656041/01-daily-ui-design-challenge-leaderboard-day-019.png",
    "description": "Hey, This is my take on Daily UI challenge #019\n\nLeaderboard\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19656041/02-daily-ui-design-challenge-leaderboard-day-019.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19656041",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #019</p><p>Leaderboard</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19627180",
    "title": "Octane - Social Media Analytics",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19627180/00-card-octane-social-media-analytics.webp",
    "coverImageUrl": "/portfolio/dribbble/19627180/01-octane-social-media-analytics.png",
    "description": "Hey everyone !\n\nOctane is a social media analytics app that delivers user stats for individual social media accounts.Users may sign in using their own social accounts, and Octane will let you monitor their social media accounts in real time and with precision, including interaction, subscriber or follower count, and audience analytics.It may be used by any individual, social media developer, or corporation to increase their exposure.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19627180/02-octane-social-media-analytics.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19627180",
        "content": "<h2>Overview</h2><p>Hey everyone !</p><p>Octane is a social media analytics app that delivers user stats for individual social media accounts.Users may sign in using their own social accounts, and Octane will let you monitor their social media accounts in real time and with precision, including interaction, subscriber or follower count, and audience analytics.It may be used by any individual, social media developer, or corporation to increase their exposure.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19617395",
    "title": "Daily UI Design Challenge | Analytics Chart | Day 018",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19617395/00-card-daily-ui-design-challenge-analytics-chart-day-018.webp",
    "coverImageUrl": "/portfolio/dribbble/19617395/01-daily-ui-design-challenge-analytics-chart-day-018.png",
    "description": "Hey, This is my take on Daily UI challenge #018\n\nAnalytics Chart\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19617395/02-daily-ui-design-challenge-analytics-chart-day-018.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19617395",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #018</p><p>Analytics Chart</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19610487",
    "title": "Daily UI Design Challenge | Email Receipt | Day 017",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19610487/00-card-daily-ui-design-challenge-email-receipt-day-017.webp",
    "coverImageUrl": "/portfolio/dribbble/19610487/01-daily-ui-design-challenge-email-receipt-day-017.png",
    "description": "Hey, This is my take on Daily UI challenge #017\n\nEmail Receipt\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19610487/02-daily-ui-design-challenge-email-receipt-day-017.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19610487",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #017</p><p>Email Receipt</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19582729",
    "title": "Daily UI Design Challenge | Popup/Overlay | Day 016",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19582729/00-card-daily-ui-design-challenge-popupoverlay-day-016.webp",
    "coverImageUrl": "/portfolio/dribbble/19582729/01-daily-ui-design-challenge-popupoverlay-day-016.png",
    "description": "Hey, This is my take on Daily UI challenge #016\n\nPopup/Overlay\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19582729/02-daily-ui-design-challenge-popupoverlay-day-016.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19582729",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #016</p><p>Popup/Overlay</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19582445",
    "title": "Daily UI Design Challenge | On Off Switch | Day 015",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19582445/00-card-daily-ui-design-challenge-on-off-switch-day-015.webp",
    "coverImageUrl": "/portfolio/dribbble/19582445/01-daily-ui-design-challenge-on-off-switch-day-015.gif",
    "description": "Hey, This is my take on Daily UI challenge #015\n\nOn Off Switch\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19582445/02-daily-ui-design-challenge-on-off-switch-day-015.gif"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19582445",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #015</p><p>On Off Switch</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19580876",
    "title": "Daily UI Design Challenge | Countdown Timer | Day 014",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19580876/00-card-daily-ui-design-challenge-countdown-timer-day-014.webp",
    "coverImageUrl": "/portfolio/dribbble/19580876/01-daily-ui-design-challenge-countdown-timer-day-014.png",
    "description": "Hey, This is my take on Daily UI challenge #014\n\nCountdown Timer\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19580876/02-daily-ui-design-challenge-countdown-timer-day-014.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19580876",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #014</p><p>Countdown Timer</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19543185",
    "title": "Daily UI Design Challenge | Direct Message | Day 013",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19543185/00-card-daily-ui-design-challenge-direct-message-day-013.webp",
    "coverImageUrl": "/portfolio/dribbble/19543185/01-daily-ui-design-challenge-direct-message-day-013.png",
    "description": "Hey, This is my take on Daily UI challenge #013\n\nDirect Message\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19543185/02-daily-ui-design-challenge-direct-message-day-013.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19543185",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #013</p><p>Direct Message</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19542816",
    "title": "Daily UI Design Challenge | E-Commerce Shop | Day 012",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19542816/00-card-daily-ui-design-challenge-e-commerce-shop-day-012.webp",
    "coverImageUrl": "/portfolio/dribbble/19542816/01-daily-ui-design-challenge-e-commerce-shop-day-012.png",
    "description": "Hey, This is my take on Daily UI challenge #012\n\nE-Commerce Shopping Page\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19542816/02-daily-ui-design-challenge-e-commerce-shop-day-012.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19542816",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #012</p><p>E-Commerce Shopping Page</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19533339",
    "title": "Daily UI Design Challenge | Flash Message | Day 011",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19533339/00-card-daily-ui-design-challenge-flash-message-day-011.webp",
    "coverImageUrl": "/portfolio/dribbble/19533339/01-daily-ui-design-challenge-flash-message-day-011.png",
    "description": "Hey, This is my take on Daily UI challenge #011\n\nFlash Message - Success & Error\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19533339/02-daily-ui-design-challenge-flash-message-day-011.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19533339",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #011</p><p>Flash Message - Success &amp; Error</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19515820",
    "title": "Daily UI Design Challenge | Share | Day 010",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19515820/00-card-daily-ui-design-challenge-share-day-010.webp",
    "coverImageUrl": "/portfolio/dribbble/19515820/01-daily-ui-design-challenge-share-day-010.png",
    "description": "Hey, This is my take on Daily UI challenge #010\n\nShare Button\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19515820/02-daily-ui-design-challenge-share-day-010.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19515820",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #010</p><p>Share Button</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19510888",
    "title": "Daily UI Design Challenge | Music Player | Day 09",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19510888/00-card-daily-ui-design-challenge-music-player-day-09.webp",
    "coverImageUrl": "/portfolio/dribbble/19510888/01-daily-ui-design-challenge-music-player-day-09.png",
    "description": "Hey, This is my take on Daily UI challenge #09\n\nMusic Player\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19510888/02-daily-ui-design-challenge-music-player-day-09.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19510888",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #09</p><p>Music Player</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19478582",
    "title": "Daily UI Design Challenge | Error 404 Page | Day 08",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19478582/00-card-daily-ui-design-challenge-error-404-page-day-08.webp",
    "coverImageUrl": "/portfolio/dribbble/19478582/01-daily-ui-design-challenge-error-404-page-day-08.png",
    "description": "Hey, This is my take on Daily UI challenge #08\n\nError 404 Page\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19478582/02-daily-ui-design-challenge-error-404-page-day-08.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19478582",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #08</p><p>Error 404 Page</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19470909",
    "title": "Daily UI Design Challenge | Settings | Day 07",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19470909/00-card-daily-ui-design-challenge-settings-day-07.webp",
    "coverImageUrl": "/portfolio/dribbble/19470909/01-daily-ui-design-challenge-settings-day-07.png",
    "description": "Hey, This is my take on Daily UI challenge #07\n\nSettings\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19470909/02-daily-ui-design-challenge-settings-day-07.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19470909",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #07</p><p>Settings</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19469398",
    "title": "Daily UI Design Challenge | User Profile | Day 06",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19469398/00-card-daily-ui-design-challenge-user-profile-day-06.webp",
    "coverImageUrl": "/portfolio/dribbble/19469398/01-daily-ui-design-challenge-user-profile-day-06.png",
    "description": "Hey, This is my take on Daily UI challenge #06\n\nUser Profile\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19469398/02-daily-ui-design-challenge-user-profile-day-06.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19469398",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #06</p><p>User Profile</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19462636",
    "title": "Daily UI Design Challenge | App Icon | Day 05",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19462636/00-card-daily-ui-design-challenge-app-icon-day-05.webp",
    "coverImageUrl": "/portfolio/dribbble/19462636/01-daily-ui-design-challenge-app-icon-day-05.png",
    "description": "Hey, This is my take on Daily UI challenge #05\n\nApp Icon\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19462636/02-daily-ui-design-challenge-app-icon-day-05.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19462636",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #05</p><p>App Icon</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19462165",
    "title": "Daily UI Design Challenge | Calculator | Day 04",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19462165/00-card-daily-ui-design-challenge-calculator-day-04.webp",
    "coverImageUrl": "/portfolio/dribbble/19462165/01-daily-ui-design-challenge-calculator-day-04.png",
    "description": "Hey, This is my take on Daily UI challenge #04\n\nCalculator\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19462165/02-daily-ui-design-challenge-calculator-day-04.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19462165",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #04</p><p>Calculator</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19459765",
    "title": "Daily UI Design Challenge | Landing Page | Day 03",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19459765/00-card-daily-ui-design-challenge-landing-page-day-03.webp",
    "coverImageUrl": "/portfolio/dribbble/19459765/01-daily-ui-design-challenge-landing-page-day-03.png",
    "description": "Hey, This is my take on Daily UI challenge #03\n\nLanding Page for a furniture website\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19459765/02-daily-ui-design-challenge-landing-page-day-03.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19459765",
        "content": "<h2>Overview</h2><p>Hey, This is my take on Daily UI challenge #03</p><p>Landing Page for a furniture website</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19458063",
    "title": "Daily UI Design Challenge | Credit Card Checkout | Day 02",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19458063/00-card-daily-ui-design-challenge-credit-card-checkout-day-02.webp",
    "coverImageUrl": "/portfolio/dribbble/19458063/01-daily-ui-design-challenge-credit-card-checkout-day-02.png",
    "description": "Hey, Continuing my Daily UI challenge #02\n\nCredit Card Checkout for a Food Joint\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19458063/02-daily-ui-design-challenge-credit-card-checkout-day-02.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19458063",
        "content": "<h2>Overview</h2><p>Hey, Continuing my Daily UI challenge #02</p><p>Credit Card Checkout for a Food Joint</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19445081",
    "title": "Daily UI Design Challenge | Sign Up Page | Day 01",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19445081/00-card-daily-ui-design-challenge-sign-up-page-day-01.webp",
    "coverImageUrl": "/portfolio/dribbble/19445081/01-daily-ui-design-challenge-sign-up-page-day-01.png",
    "description": "Hey, This is my first day of Daily UI challenge #01\n\nSign Up Page for a Meditation Program Website\n\nDo let me know what you think about it.\n\nThanks!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19445081/02-daily-ui-design-challenge-sign-up-page-day-01.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19445081",
        "content": "<h2>Overview</h2><p>Hey, This is my first day of Daily UI challenge #01</p><p>Sign Up Page for a Meditation Program Website</p><p>Do let me know what you think about it.</p><p>Thanks!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19411568",
    "title": "Quest - Smart Home App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19411568/00-card-quest-smart-home-app.webp",
    "coverImageUrl": "/portfolio/dribbble/19411568/01-quest-smart-home-app.png",
    "description": "Hello everyone!\n\nQuest is a smart home app that allows users to manage all of their smart home devices from a single app.\n\nUsers may take control of all of their devices and manage them conveniently.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19411568/02-quest-smart-home-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19411568",
        "content": "<h2>Overview</h2><p>Hello everyone!</p><p>Quest is a smart home app that allows users to manage all of their smart home devices from a single app.</p><p>Users may take control of all of their devices and manage them conveniently.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-19332254",
    "title": "Passkey - Your password manager",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/19332254/00-card-passkey-your-password-manager.webp",
    "coverImageUrl": "/portfolio/dribbble/19332254/01-passkey-your-password-manager.png",
    "description": "Hello everyone!\n\nPasskey is a password management tool that allows users to keep all of their passwords in one place.\n\nUsers may use the app to securely save passwords for multiple apps, websites, and payment systems.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/19332254/02-passkey-your-password-manager.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-19332254",
        "content": "<h2>Overview</h2><p>Hello everyone!</p><p>Passkey is a password management tool that allows users to keep all of their passwords in one place.</p><p>Users may use the app to securely save passwords for multiple apps, websites, and payment systems.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18615318",
    "title": "Arc - Buy and Rent Houses",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18615318/00-card-arc-buy-and-rent-houses.webp",
    "coverImageUrl": "/portfolio/dribbble/18615318/01-arc-buy-and-rent-houses.png",
    "description": "Hey everyone !\n\nArc is a platform that makes it incredibly simple to buy and rent homes, apartments, and commercial spaces.\n\nCompare all of the information quickly to determine the best option for you.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18615318/02-arc-buy-and-rent-houses.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18615318",
        "content": "<h2>Overview</h2><p>Hey everyone !</p><p>Arc is a platform that makes it incredibly simple to buy and rent homes, apartments, and commercial spaces.</p><p>Compare all of the information quickly to determine the best option for you.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18598583",
    "title": "Upstake - Digital Marketing",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18598583/00-card-upstake-digital-marketing.webp",
    "coverImageUrl": "/portfolio/dribbble/18598583/01-upstake-digital-marketing.png",
    "description": "Hey everyone !\n\nUpstake is a digital marketing website that offers a variety of services including E-Commerce, SEO, Website Design, and Social Media Marketing.\n\nThe design is my interpretation of how a digital marketing website should look.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18598583/02-upstake-digital-marketing.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18598583",
        "content": "<h2>Overview</h2><p>Hey everyone !</p><p>Upstake is a digital marketing website that offers a variety of services including E-Commerce, SEO, Website Design, and Social Media Marketing.</p><p>The design is my interpretation of how a digital marketing website should look.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18522231",
    "title": "Furnituraa - Online Furniture Store",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18522231/00-card-furnituraa-online-furniture-store.webp",
    "coverImageUrl": "/portfolio/dribbble/18522231/01-furnituraa-online-furniture-store.png",
    "description": "Hey everyone !\n\nFurnituraa is an online furniture business that prides itself on offering high-quality items and services to its customers.\n\nThe user interface for their website's home page is seen above.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18522231/02-furnituraa-online-furniture-store.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18522231",
        "content": "<h2>Overview</h2><p>Hey everyone !</p><p>Furnituraa is an online furniture business that prides itself on offering high-quality items and services to its customers.</p><p>The user interface for their website&#39;s home page is seen above.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18471746",
    "title": "Messaging App",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18471746/00-card-messaging-app.webp",
    "coverImageUrl": "/portfolio/dribbble/18471746/01-messaging-app.png",
    "description": "Hello, everyone!\n\nThis is an idea for a messaging app I recently created.\n\nIn recent months, I've used a number of messaging applications, and many of them lack fundamental user experience.\n\nPlease let me know what you think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18471746/02-messaging-app.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18471746",
        "content": "<h2>Overview</h2><p>Hello, everyone!</p><p>This is an idea for a messaging app I recently created.</p><p>In recent months, I&#39;ve used a number of messaging applications, and many of them lack fundamental user experience.</p><p>Please let me know what you think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18408482",
    "title": "Sub. - Subscription Manager",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18408482/00-card-sub-subscription-manager.webp",
    "coverImageUrl": "/portfolio/dribbble/18408482/01-sub-subscription-manager.png",
    "description": "Hey everyone !\n\nSub. is a subscription manager that lets you manage all of your services in one place. It assists you in keeping track of active subscriptions as well as other services such as tracking your expenditures, reminding you of renewal dates, and managing them.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18408482/02-sub-subscription-manager.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18408482",
        "content": "<h2>Overview</h2><p>Hey everyone !</p><p>Sub. is a subscription manager that lets you manage all of your services in one place. It assists you in keeping track of active subscriptions as well as other services such as tracking your expenditures, reminding you of renewal dates, and managing them.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18390046",
    "title": "Mutual - Find your mentor",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18390046/00-card-mutual-find-your-mentor.webp",
    "coverImageUrl": "/portfolio/dribbble/18390046/01-mutual-find-your-mentor.png",
    "description": "Hey everyone !\n\nMutual is a mentoring app that brings together a variety of mentees and mentors under one roof. The app allows mentees to connect with experts in various industries and mentors to share their expertise in a variety of ways. The program also offers a community for users to help them discover what they're looking for and a platform for mentors to create lectures or clips and share them with a broader audience.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18390046/02-mutual-find-your-mentor.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18390046",
        "content": "<h2>Overview</h2><p>Hey everyone !</p><p>Mutual is a mentoring app that brings together a variety of mentees and mentors under one roof. The app allows mentees to connect with experts in various industries and mentors to share their expertise in a variety of ways. The program also offers a community for users to help them discover what they&#39;re looking for and a platform for mentors to create lectures or clips and share them with a broader audience.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18381756",
    "title": "The Shoe Shack - Your place to buy shoes",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18381756/00-card-the-shoe-shack-your-place-to-buy-shoes.webp",
    "coverImageUrl": "/portfolio/dribbble/18381756/01-the-shoe-shack-your-place-to-buy-shoes.png",
    "description": "Hello, everyone!\n\nThe Shoe Shack is a local shoe store with a website that allows customers to shop for their favourite shoes all in one place.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18381756/02-the-shoe-shack-your-place-to-buy-shoes.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18381756",
        "content": "<h2>Overview</h2><p>Hello, everyone!</p><p>The Shoe Shack is a local shoe store with a website that allows customers to shop for their favourite shoes all in one place.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18380780",
    "title": "Jobnxt - Get your dream job.",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18380780/00-card-jobnxt-get-your-dream-job.webp",
    "coverImageUrl": "/portfolio/dribbble/18380780/01-jobnxt-get-your-dream-job.png",
    "description": "Hello, everyone!\n\nJobnxt is an app that searches hundreds of job vacancies and always presents the user with the most carefully curated selection of options. The app considers each user's skill and accomplishments and gives them the best results possible.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18380780/02-jobnxt-get-your-dream-job.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18380780",
        "content": "<h2>Overview</h2><p>Hello, everyone!</p><p>Jobnxt is an app that searches hundreds of job vacancies and always presents the user with the most carefully curated selection of options. The app considers each user&#39;s skill and accomplishments and gives them the best results possible.</p><p>Let me know what you guys think!</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18375589",
    "title": "FoodieHub - Order from your favourite food truck",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18375589/00-card-foodiehub-order-from-your-favourite-food-truck.webp",
    "coverImageUrl": "/portfolio/dribbble/18375589/01-foodiehub-order-from-your-favourite-food-truck.png",
    "description": "Hello, everyone!\n\nFoodieHub is an app that brings together all of the city's food trucks on one platform. Users may order their favorite food from any of their favorite food trucks and pick it up whenever convenient for them.\n\nLet me know what you guys think!\n\nEditEdit shot detailsDelete",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18375589/02-foodiehub-order-from-your-favourite-food-truck.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18375589",
        "content": "<h2>Overview</h2><p>Hello, everyone!</p><p>FoodieHub is an app that brings together all of the city&#39;s food trucks on one platform. Users may order their favorite food from any of their favorite food trucks and pick it up whenever convenient for them.</p><p>Let me know what you guys think!</p><p>EditEdit shot detailsDelete</p>"
      }
    ]
  },
  {
    "id": "dribbble-shot-18372504",
    "title": "Card Expense - Track . Manage . Pay",
    "category": "Dribbble",
    "year": "2026",
    "imageUrl": "/portfolio/dribbble/18372504/00-card-card-expense-track-manage-pay.webp",
    "coverImageUrl": "/portfolio/dribbble/18372504/01-card-expense-track-manage-pay.png",
    "description": "Hello, everyone!\n\nCard Expense is a new user-friendly app that allows users to keep track of their card spending, manage multiple cards at once, and conveniently pay their debts.\n\nLet me know what you guys think!",
    "tags": [],
    "galleryImages": [
      "/portfolio/dribbble/18372504/02-card-expense-track-manage-pay.png"
    ],
    "contentBlocks": [
      {
        "type": "text",
        "id": "text-description-18372504",
        "content": "<h2>Overview</h2><p>Hello, everyone!</p><p>Card Expense is a new user-friendly app that allows users to keep track of their card spending, manage multiple cards at once, and conveniently pay their debts.</p><p>Let me know what you guys think!</p>"
      }
    ]
  }
];
